<template>
    <main>
      <div id="focus">
        <section id="contacts-intro">
          <div id="contacts-container">
            <h1 id="our-contacts">
              Who are the Yellow Dragons?
            </h1>
          </div>
          <h2 id="contacts-intro" @click="selectContactOption">
            We invest in new talents!
            If you want to become <br>a member of the Yellow Dragons, do not hesitate to <span class="contact-link">Contact Us</span>
          </h2>
        </section>
      </div>
      <div class="ui-tab">
        <div
          v-for="(option, index) in options"
          :key="index"
          :class="['ui-tab-item', { active: selectedOption === option }]"
          @click="changeTab(option)"
        >
          {{ option }}
        </div>
      </div>
      <div v-if="selectedOption === 'Who We Are'">
        <p class="content">At Yellow Dragons, we are a dynamic venture capital firm driven by a passion for discovering and supporting exceptional entrepreneurs. Our mission is to identify visionary leaders with groundbreaking ideas and provide them with the resources and expertise they need to turn their dreams into reality.
            With a deep understanding of the startup landscape, our experienced team is dedicated to fostering innovation and fueling the growth of our portfolio companies. We believe in the power of transformative ideas and the impact they can have on industries and society as a whole.
            What sets Yellow Dragons apart is our unwavering commitment to our portfolio companies. We go beyond financial investments by providing hands-on guidance, strategic insights, and access to our extensive network of industry influencers. Our goal is to be more than just capital providers; we aim to be trusted partners on the entrepreneurial journey.
            At Yellow Dragons, we value collaboration, transparency, and integrity. We believe in building strong relationships with our founders, working alongside them to overcome challenges and seize opportunities. Our team's diverse expertise and extensive knowledge empower us to make informed investment decisions and drive long-term success.
            Join us on the exciting adventure of discovering and supporting the next generation of visionary leaders. Whether you're an entrepreneur with a groundbreaking idea or an investor seeking compelling opportunities, Yellow Dragons is here to champion your vision and fuel your success</p>
      </div>
      <div v-else-if="selectedOption === 'Our Values'">
        <p class="content">Innovation: We embrace a culture of innovation, constantly seeking new ideas and approaches to solve complex challenges. We believe that disruptive thinking is the key to unlocking groundbreaking opportunities.
            <br><br><strong>Integrity</strong>: We uphold the highest standards of integrity in everything we do. Honesty, transparency, and ethical behavior form the foundation of our relationships with entrepreneurs, partners, and stakeholders.
            <br><br><strong>Collaboration</strong>: We foster a collaborative ecosystem, working closely with visionary entrepreneurs and industry experts to create a synergistic network. We believe that collaboration fuels growth and enables us to achieve remarkable results together.
            <br><br><strong>Excellence</strong>: We strive for excellence in all aspects of our work. From rigorous due diligence to strategic investments, we are committed to delivering exceptional value and driving the success of the ventures we support.
            <br><br><strong>Empowerment</strong>: We empower entrepreneurs to unleash their full potential. We provide not only financial resources but also mentorship, expertise, and a supportive environment to help entrepreneurs thrive and achieve their goals.
            <br><br><strong>Impact</strong>: We are driven by the desire to make a positive impact on society. We actively seek opportunities to invest in ventures that have the potential to create meaningful change, whether it's through technological advancements, social innovation, or environmental sustainability.
            <br><br><strong>Long-Term Vision</strong>: We take a long-term view of investments, focusing on sustainable growth and building enduring businesses. We understand that true success is measured by the long-term impact and value generated by our portfolio companies.
            <br><br>These values are at the heart of everything we do at Yellow Dragons. They inspire us to continuously evolve, adapt to new challenges, and make a difference in the world of venture capital.</p>
      </div>
      <div v-else-if="selectedOption === 'Contacts'">
        <Contact />
      </div>
    </main>
  </template>
  
  <script>
  
  export default {
    data() {
      return {
        options: ['Who We Are', 'Our Values', 'Contacts'],
        selectedOption: 'Who We Are' // L'opzione "Who We Are" è selezionata di default
      };
    },
    methods: {
      changeTab(option) {
        this.selectedOption = option;
      },
      selectContactOption() {
        this.changeTab('Contacts');
      }
    }
  };
  </script>
  
  <style scoped>
#contacts-container {
  display: grid;
  grid-template-columns: auto auto auto;
  flex-wrap: wrap;
  flex-direction: row;
  justify-content: center;
  align-content: flex-start;
  justify-content: space-between;
  padding-left: 10%;
  padding-right: 10%;
}

#focus {
  background-image: url("@/assets/img/areas_background.jpg");
  background-size: cover;
  width: 100vw;
  height: 60vh;
  background-position-y: 65%;
  display: flex;
  flex-direction: row;
  align-items: center;
  justify-content: flex-end;
  color: white;
}

#contacts-intro {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  width: 50vw;
  margin-right: 5%;
}

#contacts-container {
  text-align: right;
  margin-bottom: 20px;
}

#our-contacts {
  font-size: 48px;
  font-weight: bold;
  margin-bottom: 20px;
  border: 7px solid white;
  width: 100%;
  text-align: center;
  padding: 20px;
}

#contacts-introduction {
  text-align: center;
  padding: 30px;
}

.ui-tab {
  display: flex;
  background-color: #f0f0f0;
  border-radius: 4px;
  overflow: hidden;
}

.ui-tab-item {
  padding: 12px 20px;
  font-size: 15px;
  font-weight: bolder;
  cursor: pointer;
  transition: background-color 0.3s;
}

.ui-tab-item:hover {
  opacity: 0.7;
}

.ui-tab-item.active {
  background-color: rgb(108, 171, 192);
  color: rgb(228, 237, 238);
}

.content {
  padding: 20px;
  line-height: 1.2;
  font-size: 15px;
}

.area-image {
  margin-top: 20px;
}

#image-text-container {
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
  align-items: center;
  margin-top: 20px;
}

.image-container {
  width: 100px;
  height: 100px;
}

.text-container {
  margin-top: 10px;
}

.img {
  width: 80px;
  height: 80px;
  object-fit: cover;
}

h3 {
  font-size: 18px;
  font-weight: bold;
  margin-bottom: 5px;
}

p {
  font-size: 14px;
}

.contact-link {
  text-decoration: underline;
  cursor: pointer;
}

.contact-link:hover {
  opacity: 0.7;
}
  </style>
  